# Generated by Django 5.0.7 on 2024-08-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('paid', 'Paid Leave')], default='casual', max_length=25, null=True),
        ),
    ]
