# Generated by Django 5.1 on 2024-08-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('paid', 'Paid Leave')], default='pending', max_length=10),
        ),
    ]
