# Generated by Django 5.1 on 2024-08-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('cancelled', 'Cencelled'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
