# Generated by Django 5.1 on 2024-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'employee'), (1, 'admin'), (3, 'manager')], default=1, max_length=50),
        ),
    ]
