# Generated by Django 5.1 on 2024-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'employee'), (3, 'manager')], default=1, max_length=50),
        ),
    ]
