# Generated by Django 5.1 on 2024-08-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='admin',
        ),
    ]
