# Generated by Django 5.1 on 2024-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_user_employee_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'employee'), (3, 'manager')], default=1),
        ),
    ]
