# Generated by Django 5.1 on 2024-08-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='admin',
            new_name='user',
        ),
    ]
