# Generated by Django 5.1 on 2024-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_admin_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familycontact',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='admin',
        ),
        migrations.AddField(
            model_name='employee',
            name='casual_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
