# Generated by Django 5.1 on 2024-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_admin_familycontact_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='casual_leave_balance',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paid_leave_balance',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
