# Generated by Django 5.1 on 2024-08-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_education_graduation_result_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_blocked',
            new_name='is_active',
        ),
    ]
